### ISSUE TITLE
Multiple build errors

### ISSUE THREAD

**Issue by peerchemist** [seyhajin/webgpu-wasm-c#1]
Hello, I am trying to compile this, but there are a number of build errors. Care to take a look and propose fixes?

```
main.c:128:71: error: use of undeclared identifier 'false'; did you mean 'fclose'?
  128 |     emscripten_set_resize_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, 0, false, resize);
      |                                                                       ^~~~~
      |                                                                       fclose
/home/cookie/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/html5.h:442:174: note: expanded from macro 'emscripten_set_resize_callback'
  442 | #define emscripten_set_resize_callback(target, userData, useCapture, callback)                emscripten_set_resize_callback_on_thread(               (target), (userData), (useCapture), (callback), EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD)
      |                                                                                                                                                                              ^
/home/cookie/emsdk/upstream/emscripten/cache/sysroot/include/stdio.h:82:5: note: 'fclose' declared here
   82 | int fclose(FILE *);
      |     ^
main.c:128:5: error: incompatible pointer to integer conversion passing 'int (FILE *)' (aka 'int (struct _IO_FILE *)') to parameter of type 'int' [-Wint-conversion]
  128 |     emscripten_set_resize_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, 0, false, resize);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cookie/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/html5.h:442:173: note: expanded from macro 'emscripten_set_resize_callback'
  442 | #define emscripten_set_resize_callback(target, userData, useCapture, callback)                emscripten_set_resize_callback_on_thread(               (target), (userData), (useCapture), (callback), EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD)
      |                                                                                                                                                                             ^~~~~~~~~~~~
/home/cookie/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/html5.h:177:129: note: passing argument to parameter 'useCapture' here
  177 | EMSCRIPTEN_RESULT emscripten_set_resize_callback_on_thread(const char *target __attribute__((nonnull)), void *userData, EM_BOOL useCapture, em_ui_callback_func callback, pthread_t targetThread);
      |                                                                                                                                 ^
main.c:222:39: error: use of undeclared identifier 'false'; did you mean 'else'?
  222 |             .alphaToCoverageEnabled = false,
      |                                       ^~~~~
      |                                       else
main.c:222:39: error: expected expression
4 errors generated.
```

**Comment by seyhajin** [comment]
Hi, can you specify the version of Emscripten you are using ? On my side, it worked on version 3.1.51.
Try including the header "<stdbool.h> to your code.

**Comment by peerchemist** [comment]
Thanks, adding stdbool.h fixes it.

Emescripten 3.1.59
